#!/bin/bash
# @parseArger-begin
# @parseArger-help "create an agent" --option "help" --short-option "h"
# @parseArger-verbose --option "verbose" --level "0" --quiet-option "quiet"
_has_colors=0
if [ -t 1 ]; then # Check if stdout is a terminal
	ncolors=$(tput colors 2>/dev/null)
	if [ -n "$ncolors" ] && [ "$ncolors" -ge 8 ]; then
		_has_colors=1
	fi
fi
# @parseArger-declarations
# @parseArger pos name "agent name"
# @parseArger opt prompt "agent system prompt"
# @parseArger opt provider "llm provider"
# @parseArger opt model "llm model"
# @parseArger opt temperature "temperature"
# @parseArger-declarations-end

# @parseArger-utils
_helpHasBeenPrinted=1;
_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)";
# @parseArger-utils-end

# @parseArger-parsing

__cli_arg_count=$#;

die()
{
	local _ret=1
    if [[ -n "$2" ]] && [[ "$2" =~ ^[0-9]+$ ]]; then
   	_ret="$2"
    fi
	test "${_PRINT_HELP:-no}" = yes && print_help >&2
	log "$1" -3 >&2
	exit "${_ret}"
}


begins_with_short_option()
{
	local first_option all_short_options=''
	first_option="${1:0:1}"
	test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
}

# POSITIONALS ARGUMENTS
_positionals=();
_optional_positionals=();
_arg_name="";
# OPTIONALS ARGUMENTS
_arg_prompt=
_arg_provider=
_arg_model=
_arg_temperature=
# FLAGS
# NESTED
_verbose_level="0";



print_help()
{
	_triggerSCHelp=1;

	if [[ "$_helpHasBeenPrinted" == "1" ]]; then
		_helpHasBeenPrinted=0;
		echo -e "create an agent:"
	echo -e "	name: agent name"
	echo -e "	--prompt <prompt>: agent system prompt"
	echo -e "	--provider <provider>: llm provider"
	echo -e "	--model <model>: llm model"
	echo -e "	--temperature <temperature>: temperature"
	echo -e "Usage :
	$0 <name> [--prompt <value>] [--provider <value>] [--model <value>] [--temperature <value>]";
	fi

}

log() {
	local _arg_msg="${1}";
	local _arg_level="${2:-0}";
	if [ "${_arg_level}" -le "${_verbose_level}" ]; then
		case "$_arg_level" in
			-3)
				_arg_COLOR="[0;31m";
				;;
			-2)
				_arg_COLOR="[0;33m";
				;;
			-1)
				_arg_COLOR="[1;33m";
				;;
			1)
				_arg_COLOR="[0;32m";
				;;
			2)
				_arg_COLOR="[1;36m";
				;;
			3)
				_arg_COLOR="[0;36m";
				;;
			*)
				_arg_COLOR="[0m";
				;;
		esac
		if [ "${_has_colors}" == "1" ]; then
			echo -e "${_arg_COLOR}${_arg_msg}[0m";
		else
			echo "${_arg_msg}";
		fi
	fi
}

parse_commandline()
{
	_positionals_count=0
	while test $# -gt 0
	do
		_key="$1"
		case "$_key" in
			--prompt)
				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
				_arg_prompt="$2"
				shift
				;;
			--prompt=*)
				_arg_prompt="${_key##--prompt=}"
				;;
			
			--provider)
				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
				_arg_provider="$2"
				shift
				;;
			--provider=*)
				_arg_provider="${_key##--provider=}"
				;;
			
			--model)
				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
				_arg_model="$2"
				shift
				;;
			--model=*)
				_arg_model="${_key##--model=}"
				;;
			
			--temperature)
				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
				_arg_temperature="$2"
				shift
				;;
			--temperature=*)
				_arg_temperature="${_key##--temperature=}"
				;;
			
			-h|--help)
				print_help;
				exit 0;
				;;
			-h*)
				print_help;
				exit 0;
				;;
			--verbose)
					if [ $# -lt 2 ];then
						_verbose_level="$((_verbose_level + 1))";
					else
						_verbose_level="$2";
						shift;
					fi
					;;
				--quiet)
					if [ $# -lt 2 ];then
						_verbose_level="$((_verbose_level - 1))";
					else
						_verbose_level="-$2";
						shift;
					fi
					;;
				
				*)
				_last_positional="$1"
				_positionals+=("$_last_positional")
				_positionals_count=$((_positionals_count + 1))
				;;
		esac
		shift
	done
}


handle_passed_args_count()
{
	local _required_args_string="name"
	if [ "${_positionals_count}" -gt 1 ] && [ "$_helpHasBeenPrinted" == "1" ];then
		_PRINT_HELP=yes die "FATAL ERROR: There were spurious positional arguments --- we expect at most 1 (namely: $_required_args_string), but got ${_positionals_count} (the last one was: '${_last_positional}').
	${_positionals[*]}" 1
	fi
	if [ "${_positionals_count}" -lt 1 ] && [ "$_helpHasBeenPrinted" == "1" ];then
		_PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require at least 1 (namely: $_required_args_string), but got only ${_positionals_count}.
	${_positionals[*]}" 1;
	fi
}


assign_positional_args()
{
	local _positional_name _shift_for=$1;
	_positional_names="_arg_name ";
	shift "$_shift_for"
	for _positional_name in ${_positional_names};do
		test $# -gt 0 || break;
		eval "if [ \"\$_one_of${_positional_name}\" != \"\" ];then [[ \"\${_one_of${_positional_name}[*]}\" =~ \"\${1}\" ]];fi" || die "${_positional_name} must be one of: $(eval "echo \"\${_one_of${_positional_name}[*]}\"")" 1;
		eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an ParseArger bug." 1;
		shift;
	done
}

print_debug()
{
	print_help
	# shellcheck disable=SC2145
	echo "DEBUG: $0 $@";
	
	echo -e "	name: ${_arg_name}";
	echo -e "	prompt: ${_arg_prompt}";
	echo -e "	provider: ${_arg_provider}";
	echo -e "	model: ${_arg_model}";
	echo -e "	temperature: ${_arg_temperature}";

}


on_interrupt() {
	die Process aborted! 130;
}


parse_commandline "$@";
handle_passed_args_count;
assign_positional_args 1 "${_positionals[@]}";
trap on_interrupt INT;



# @parseArger-parsing-end
# print_debug "$@"
# @parseArger-end

source "$_SCRIPT_DIR/../lib/errors"

config_dir="$HOME/.config/ai-gents/agents"
config_file="$config_dir/${_arg_name}.yml"

# Validate agent name is safe for filenames
if [[ "$_arg_name" =~ [\/\\:\*\?\"\<\>\|] ]]; then
    die "Invalid agent name: contains unsafe characters" $E_VALIDATION_ERROR
fi

# Validate prompt is safe for YAML (basic check)
if [[ -n "$_arg_prompt" ]] && [[ "$_arg_prompt" =~ $'\n' ]]; then
    die "Invalid prompt: newlines not allowed in system prompt" $E_VALIDATION_ERROR
fi

# Copy base template using yq with --arg for safety
yq --arg name "$_arg_name" ".name = \$name" "$SCRIPT_DIR/../../../agent.yml" > "$config_file"

# Update optional fields if provided using yq --arg (no string interpolation)
if [ -n "$_arg_prompt" ]; then
    yq -i --arg prompt "$_arg_prompt" ".system.prompt = \$prompt" "$config_file"
fi

if [ -n "$_arg_provider" ]; then
    yq -i --arg provider "$_arg_provider" ".model.provider = \$provider" "$config_file"
fi

if [ -n "$_arg_model" ]; then
    yq -i --arg model "$_arg_model" ".model.name = \$model" "$config_file"
fi

if [ -n "$_arg_temperature" ]; then
    # Validate temperature is numeric before passing
    if [[ "$_arg_temperature" =~ ^[0-9]+(\.[0-9]+)?$ ]]; then
        yq -i --arg temp "$_arg_temperature" ".model.temperature = \$temp" "$config_file"
    else
        warn "Invalid temperature value, skipping"
    fi
fi

log "Agent '${_arg_name}' created at ${config_file}" 1


